# Generated by Django 4.0.2 on 2022-02-21 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, unique=True)),
                ('about', models.TextField(max_length=500)),
                ('video', models.FileField(upload_to='video/')),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('source', models.URLField(null=True)),
            ],
        ),
    ]
